"""empty message

Revision ID: 9bba1bdbb488
Revises: bad55b628de5
Create Date: 2024-12-18 12:56:47.933302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bba1bdbb488'
down_revision = 'bad55b628de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid', sa.Float(precision=2), nullable=True))
        batch_op.add_column(sa.Column('consumed', sa.Float(precision=2), nullable=True))
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('is_payer')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.REAL(), autoincrement=False, nullable=False))

    with op.batch_alter_table('transaction_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_payer', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('amount_paid', sa.REAL(), autoincrement=False, nullable=True))
        batch_op.drop_column('consumed')
        batch_op.drop_column('paid')

    # ### end Alembic commands ###
